// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

function getUser(param) {
  return {
    id: 1,
    name: "Bob",
    isActive: true,
  };
}

var Utilities = {
  getUser: getUser,
};

export { Utilities };
/* No side effect */
